name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main  # Change 'main' to your repository's main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build steps here. For example, if you're using Node.js:
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path/to/your/build/folder  # Replace with the folder containing the build output
